name: HydroEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - affine=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py39h72bdee0_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.3.2=h166bdaf_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.74.0=h6cacc03_7
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - cryptography=38.0.4=py39hd97740a_0
  - curl=7.82.0=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39hb9d737c_1
  - dask=2023.2.0=pyhd8ed1ab_0
  - dask-core=2023.2.0=pyhd8ed1ab_0
  - dask-glm=0.2.0=py_1
  - dask-jobqueue=0.8.1=pyhd8ed1ab_0
  - dask-ml=2022.5.27=pyhd8ed1ab_0
  - dask-searchcv=0.2.0=py_0
  - dask-xgboost=0.1.11=pyh9f0ad1d_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2023.2.0=pyhd8ed1ab_0
  - earthengine-api=0.1.339=pyhd8ed1ab_1
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fiona=1.8.21=py39hc5a795b_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39hb9d737c_1
  - freetype=2.12.1=hca18f0e_1
  - freexl=1.0.6=h166bdaf_1
  - frozenlist=1.3.3=py39hb9d737c_0
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.4.2=py39hc691d54_1
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.10.2=h9c3ff4c_0
  - geotiff=1.7.1=h509b78c_1
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - google-api-core=2.11.0=pyhd8ed1ab_0
  - google-api-python-client=2.77.0=pyhd8ed1ab_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=2.3.2=pyhd8ed1ab_0
  - google-cloud-storage=2.7.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py39h8db88ab_4
  - google-resumable-media=2.4.1=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - grpcio=1.51.1=py39h712372c_0
  - gst-plugins-base=1.20.1=hcf0ee16_1
  - gstreamer=1.20.3=hd4edc92_2
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.1=nompi_h2386368_104
  - heapdict=1.0.1=py_0
  - httplib2=0.21.0=pyhd8ed1ab_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - ipython=8.10.0=pyh41d4057_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json-c=0.15=h98cffda_0
  - jupyter_client=8.1.0=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py39hf3d152e_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_0
  - kealib=1.4.14=h87e4c3c_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=13.0.1=default_hc23dcda_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.82.0=h7bff187_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgdal=3.4.2=h886d1c3_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libllvm13=13.0.1=hf817b99_2
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.21.12=h3eb15da_0
  - librttopo=1.1.0=hf69c175_9
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=ha867d66_15
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h82bc61c_5
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.7.1=cpu_ha3b9936_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=haae042b_4
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=h166bdaf_4
  - lightgbm=3.3.5=py39h227be39_0
  - llvmlite=0.39.1=py39h7d9a04d_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py39h724f13c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib=3.6.3=py39hf3d152e_0
  - matplotlib-base=3.6.3=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py39hf939315_1
  - multidict=6.0.4=py39h72bdee0_0
  - multipledispatch=0.6.0=py_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.3=h27087fc_1
  - networkx=3.0=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.88=he45b914_0
  - numba=0.56.4=py39h61ddf18_0
  - numpy=1.23.5=py39h3d75532_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1t=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ad29b5_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hf3a2cdf_3
  - pip=23.0=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=22.01.0=h1434ded_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=14.5=hfdbbde3_0
  - proj=9.0.0=h93bde94_1
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.7.1=cpu_py39h4655687_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py39hcadae2f_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.10=h85951f9_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - qt=5.12.9=h1304e3e_6
  - rasterio=1.2.10=py39h2e4b6e6_5
  - re2=2022.06.01=h27087fc_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rioxarray=0.13.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - rtree=1.0.1=py39hb102c33_1
  - scikit-learn=1.2.1=py39h86b2a18_0
  - scipy=1.10.0=py39h7360e5f_2
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - shapely=1.8.1=py39h73b9895_0
  - simplejson=3.18.3=py39h72bdee0_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_2
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h2ae25f5_2
  - swifter=1.3.4=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.7.2=h1e4a385_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzcode=2022g=h166bdaf_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xarray=2023.2.0=pyhd8ed1ab_0
  - xerces-c=3.2.3=h8ce2273_4
  - xgboost=1.7.1=cpu_py39h4655687_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.2=py39hb9d737c_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.13.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - argon2-cffi==21.1.0
    - bleach==4.1.0
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - entrypoints==0.3
    - ipykernel==6.6.0
    - ipympl==0.8.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jsonschema==4.2.1
    - jupyter==1.0.0
    - jupyter-client==7.1.0
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.6
    - pandocfilters==1.5.0
    - plotly==5.4.0
    - prometheus-client==0.12.0
    - pyrsistent==0.18.0
    - pyzmq==22.3.0
    - qtconsole==5.2.1
    - qtpy==1.11.2
    - send2trash==1.8.0
    - tenacity==8.0.1
    - terminado==0.12.1
    - testpath==0.5.0
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
prefix: /projects/montimaj@colostate.edu/software/anaconda/envs/HydroEnv
